# Experiment configurations

train:
	log_every:
		batch: 1
		epoch: 1

eval:
	log_every:
		batch: -1
		epoch: 1

save_every:
	batch: -1
	epoch: -1

loader:
	shuffle: true
	num_workers: 2
	pin_memory: true