# Experiment configurations

exp_dir: null

loader:
	shuffle: true
	num_workers: 2
	pin_memory: true
	
training:
	accum_grad: 1
	stop:
		batches: 10000
		epochs: null
	log:
		batches: 1
		epoches: 1

evaluation:
	batches: -1
	epoches: 1

save_ckpt:
	batches: -1
	epochs: -1