conv:
    num_channels: "32*2"
    kernel_sizes: 3
    strides: 1
    paddings: 1
    biases: true
    pooler:
        names: "MaxPool2d AvgPool2d"
        sizes: 2
        strides: null
        paddings: 0
    normalization_layers: "BatchNorm2d"
    activations: "ReLU"

fcn:
    hidden_dims: "64 10"
    biases: true
    activations: "ReLU"