root: "./datastore/cifar10/"
output_dim: 10
to_cuda: false
batch_size: 64

sizes:
    train: 0.8
    val: 0.2
    test: 1.0

transforms:
    train:
        input:
            - name: "ToTensor"
    eval:
        input: 
            - name: "ToTensor"

objective: "CELoss"
metrics:
    - "Accuracy"
    - "F1Score"
    - "AUROC"